version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  back:
    build: ./back
    environment:
      DB_HOST: db
  front:
    build: ./front
    ports:
      - 443:443
    volumes:
      - /data/caddy:/data
